import "./style.css";
import displayHome from "./home.js";
import displayMenu from "./menu.js";
import displayReservation from "./reservation.js";
export default function () {
	const content = document.getElementById("content");
	const header = document.createElement("div");
	header.classList.add("header");
	header.textContent = "DimSum House";
	const body = document.createElement("div");
	body.id = "body";
	const heroImage = document.createElement("div");
	heroImage.id = "heroImage";
	body.appendChild(heroImage);
	const tabs = document.createElement("div");
	tabs.classList.add("tabs");
	const ul = document.createElement("ul");
	const li1 = document.createElement("li");
	li1.textContent = "tab1";
	const li2 = document.createElement("li");
	li2.textContent = "tab2";
	const li3 = document.createElement("li");
	li3.textContent = "tab3";
	ul.appendChild(li1);
	ul.appendChild(li2);
	ul.appendChild(li3);
	tabs.appendChild(ul);
	content.appendChild(header);
	content.appendChild(body);
	content.appendChild(tabs);
	li1.addEventListener("click", displayHome);
	li2.addEventListener("click", displayMenu);
	li3.addEventListener("click", displayReservation);
}
